name:  Download Trigger Manifest
description: Downloads trigger manifest artifact

runs: 
  using: "composite"
  steps:

    - name: Create artifacts folder
      run: mkdir ${{ env.ARTIFACTS_FOLDER }}

    - name: Create trigger manifest folder
      run: mkdir -p ${{ env.ARTIFACTS_FOLDER }}/${{ env.MANIFEST_FOLDER }}

    - name: Unstash trigger manifest
      uses: actions/download-artifact@v4
      with:
        name: trigger_manifest
        path: ${{ env.ARTIFACTS_FOLDER }}/${{ env.MANIFEST_FOLDER }}