name: Install Python Package
description: Install outsystems-pipeline from PyPI

runs: 
  using: "composite"
  steps:

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ vars.PYTHON_VERSION }}

    - name: Install required packages
      shell: bash
      run: pip install -U outsystems-pipeline==${{ vars.OS_PACKAGE_VERSION }}
