name: GitHub-CD-Pipeline

on:
  workflow_dispatch:
    inputs:
      TriggerManifest:
        description: 'Trigger manifest artifact (in JSON format) for the current pipeline run.'
        required: true
        type: string
      TriggeredBy:
        description: 'Name of LifeTime user that triggered the pipeline remotely.'
        required: false
        type: string

env:
  ARTIFACTS_FOLDER: ${{ vars.ARTIFACTS_FOLDER }}
  MANIFEST_FOLDER: ${{ vars.MANIFEST_FOLDER }}
  MANIFEST_FILE: ${{ vars.MANIFEST_FILE }}
  LIFETIME_HOSTNAME: ${{ vars.LIFETIME_HOSTNAME }}
  LIFETIME_API_VERSION: ${{ vars.LIFETIME_API_VERSION }}
  LIFETIME_SERVICE_ACCOUNT_TOKEN: ${{ secrets.LIFETIME_SERVICE_ACCOUNT_TOKEN }}
  ENVIRONMENT_DEVELOPMENT_LABEL: ${{ vars.ENVIRONMENT_DEVELOPMENT_LABEL }}
  ENVIRONMENT_REGRESSION_LABEL: ${{ vars.ENVIRONMENT_REGRESSION_LABEL }}
  ENVIRONMENT_ACCEPTANCE_LABEL: ${{ vars.ENVIRONMENT_ACCEPTANCE_LABEL }}
  ENVIRONMENT_PREPRODUCTION_LABEL: ${{ vars.ENVIRONMENT_PREPRODUCTION_LABEL }}
  ENVIRONMENT_PRODUCTION_LABEL: ${{ vars.ENVIRONMENT_PRODUCTION_LABEL }}
  CICD_PROBE_ENVIRONMENT_URL: ${{ vars.CICD_PROBE_ENVIRONMENT_URL }}
  BDD_FRAMEWORK_ENVIRONMENT_URL: ${{ vars.BDD_FRAMEWORK_ENVIRONMENT_URL }}
  AI_MENTOR_STUDIO_HOSTNAME: ${{ vars.AI_MENTOR_STUDIO_HOSTNAME }}
  AI_MENTOR_STUDIO_ACTIVATION_CODE: ${{ vars.AI_MENTOR_STUDIO_ACTIVATION_CODE }}
  AI_MENTOR_STUDIO_API_KEY: ${{ vars.AI_MENTOR_STUDIO_API_KEY }}
  AI_MENTOR_STUDIO_FOLDER: ${{ vars.AI_MENTOR_STUDIO_FOLDER }}
  AI_MENTOR_STUDIO_THRESHOLDS_TECHDEBT_LEVEL: "High"
  AI_MENTOR_STUDIO_THRESHOLDS_SECURITY_FINDINGS_COUNT: 10
  OS_PACKAGE_VERSION: ${{ vars.OS_PACKAGE_VERSION }}
  PYTHON_VERSION: ${{ vars.PYTHON_VERSION }}

jobs:

  code_analysis:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - uses: ./.github/actions/publish-trigger-manifest

    - uses: ./.github/actions/code-analysis

  deploy-regression:
    runs-on: ubuntu-latest
    needs: code_analysis
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./.github/actions/lifetime-deployment
        with:
          source-environment-label: ${{ env.ENVIRONMENT_DEVELOPMENT_LABEL }}
          destination-environment-label: ${{ env.ENVIRONMENT_REGRESSION_LABEL }}
          include-test-applications: true

  run_regression:
      runs-on: ubuntu-latest
      needs: deploy-regression
      steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./.github/actions/regression-testing

  deploy-acceptance:
    runs-on: ubuntu-latest
    needs: run_regression
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./.github/actions/lifetime-deployment
        with:
          source-environment-label: ${{ env.ENVIRONMENT_REGRESSION_LABEL }}
          destination-environment-label: ${{ env.ENVIRONMENT_ACCEPTANCE_LABEL }}

  deploy-dry-run:
    runs-on: ubuntu-latest
    needs: deploy-acceptance
    environment: pre-env
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./.github/actions/lifetime-deployment
        with:
          source-environment-label: ${{ env.ENVIRONMENT_ACCEPTANCE_LABEL }}
          destination-environment-label: ${{ env.ENVIRONMENT_PREPRODUCTION_LABEL }}

  deploy-production:
    runs-on: ubuntu-latest
    needs: deploy-dry-run
    environment: prd-env
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./.github/actions/lifetime-deployment
        with:
          source-environment-label: ${{ env.ENVIRONMENT_PREPRODUCTION_LABEL }}
          destination-environment-label: ${{ env.ENVIRONMENT_PRODUCTION_LABEL }}